### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by carlescufi**
Based on: https://github.com/mkuyper/mscgen/tree/python3

### CODE REVIEW

**Comment by carlescufi** [comment]
CC @llucax @mkuyper @obonaventure @gwen21

**Comment by llucax** [comment]
Thanks @carlescufi !

I can't test this right now, but if you have tested it and it's working well, I will happily merge it.

**Comment by llucax** [comment]
BTW, would you be interested in taking over the project?

**Comment by carlescufi** [comment]
@llucax 
>I can't test this right now, but if you have tested it and it's working well, I will happily merge it.

Let me run a few more comprehensive tests before you merge, I will ping you here.

>BTW, would you be interested in taking over the project?

Sure, I would. We use the extension internally and I now have the bandwidth and help within my company to drive this.

**Comment by carlescufi** [comment]
@llucax 

>I can't test this right now, but if you have tested it and it's working well, I will happily merge it.

I have now made sure all of our doc correctly generates with this patch, and it does. Feel free to merge it (and push to PyPI?)

**Comment by llucax** [comment]
> Sure, I would. We use the extension internally and I now have the bandwidth and help within my company to drive this.

That's great news!

> I have now made sure all of our doc correctly generates with this patch, and it does. Feel free to merge it (and push to PyPI?)

I will add you as an admin for the project, then you can merge it yourself. I will see if I can recover my PyPi credentials to also put you as an admin there.

**Comment by carlescufi** [comment]
> > Sure, I would. We use the extension internally and I now have the bandwidth and help within my company to drive this.
> 
> That's great news!
> 
> > I have now made sure all of our doc correctly generates with this patch, and it does. Feel free to merge it (and push to PyPI?)
> 
> I will add you as an admin for the project, then you can merge it yourself. I will see if I can recover my PyPi credentials to also put you as an admin there.

Great! I've accepted your invitation. Feel free to send credentials via email, should be in the commit message.

**Pull request merged**
